interface ElectricUnicycle {
  thumbnail: any;
  android: boolean;
  'battery-capacity': number;
  brand: string;
  'charging-time': number;
  'distance-max': number;
  'distance-min': number;
  'factory-speed': number;
  'front-light': boolean;
  gap: number;
  horn: boolean;
  id: string;
  ios: boolean;
  'ip-rating': string;
  'max-slope': number;
  'max-speed': number;
  model: string;
  'operating-temperature-low': number;
  'operating-temperature-top': number;
  output: string;
  payload: number;
  'power-rating': number;
  'rear-light': boolean;
  'tire-pressure': number;
  'tire-size': number;
  'tire-type': 'Inflatable' | 'Full' | 'Other';
  'turn-signal': boolean;
  weight: number;
  description: string;
}
